[workspace]
resolver = "3"
members = ["kernel"]

[package]
name = "basic"
version = "0.1.0"
edition = "2024"

[dependencies]
ovmf-prebuilt = "0.2.4"
pc-keyboard = "0.8.0"

[build-dependencies]
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
bootloader = "0.11.12"
